FROM node:12.16.2-alpine3.9

WORKDIR /usr/app

RUN apk add git

COPY package.json ./
COPY src/web/api ./src/web/api
COPY src/web/package.json ./src/web/package.json
COPY src/mongo ./src/mongo
RUN yarn install

EXPOSE 8080

ENV MONGO_URL="mongodb://host.docker.internal:27017/dev"
# ENV API_URL='host.docker.internal:8080'
# ENV WEBSITE_URL='host.docker.internal:3000'

CMD yarn workspace web start-api