FROM node:12.16.2-alpine3.9

WORKDIR /usr/app

RUN apk add git

COPY package.json ./
COPY src/discord_bot ./src/discord_bot
COPY src/mongo ./src/mongo
RUN yarn install

ENV MONGO_URL="mongodb://host.docker.internal:27017/dev"

CMD yarn workspace discord_bot start